services:
  ai-trs-app:
    build: .
    # ports: 
    #   - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    expose:
      - 3000
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - webnet

networks:
  webnet:
    external: true


  