services:
  app:
    image: felixokpalaima/ai-trs-app:345d7e485f1f87db67693ffa2c3ffbd9329f27a9
    expose: 
      - 3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IMAGE_TAG=${IMAGE_TAG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet

networks:
  webnet:
    external: true